export const dataContract = `
<div title="Page 1">
<div>
    <div>
        <div style="text-align: center;"><strong>THỎA THUẬN<br>BÁN HÀ** TRÊN CÁC N&Ecirc;̀N TẢNG THƯƠNG MẠI ĐIỆN TỬ - BEAUTYX&nbsp;</strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<p style="text-align: left;">&nbsp; <strong>Đây là thỏa thuận pháp lý giữa Người tiêu dùng với Công ** C&ocirc;̉ ph&acirc;̀n MYSPA (&ldquo;MYSPA&rdquo;), quy định các đi&ecirc;̀u khoản trong việc Người tiêu dùng tham gia kinh doanh các n&ecirc;̀n tảng thương mại điện tử của Myspa **** c&acirc;́p (&ldquo;Thỏa thuận&rdquo;). &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</strong></p>
            <p style="text-align: left;"><strong>Thỏa thuận này là Thỏa thuận th&ecirc;̉ hiện sự đ&ocirc;̀ng ý ti&ecirc;́n hành giao dịch dưới hình thức giao dị** điện tử giữa *** Bên của Thỏa thuận. Bằng cách tích chọn vào ô &ldquo;Tôi đ&ocirc;̀ng ý với Thỏa Thuận sử dụ** dịch vụ&rdquo; trên Thỏa thuận, Người tiêu dùng đ&ocirc;̀ng ý rằng các đi&ecirc;̀u khoản này sẽ được áp dụng n&ecirc;́u Người tiêu dùng lựa chọn truy cập hoặc sử dụng dị** vụ và thao tác tích chọn này có nghĩa là hai Bên đã đ&ocirc;̀ng ý với mọi đi&ecirc;̀u khoản của Thỏa thuận và được xem như hai Bên đã ký k&ecirc;́t Thỏa thuận.</strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p>
            <p style="text-align: left;"><strong>Thông tin Người Bán: Modern warfare II<br>Tên Người Bán: Nguy&ecirc;̃n Thị Nhung<br>Địa chỉ: 220 NGUY&Ecirc;̃N LƯƠNG BẰNG, P HÒA KHÁNH BẮC, QUẬN LIÊN CHI&Ecirc;̀U, ĐÀ NẴNG Địa chỉ URL: https://beautyx/cua-hang/dodivas</strong></p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<p style="text-align: left;"><strong>ĐI&Ecirc;̀U 1. ĐỊNH NGHĨA &nbsp;&nbsp;</strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>
            <p style="text-align: left;">***** thỏa thuận này các từ ngữ dưới đây được hi&ecirc;̉u như sau: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p>
            <p style="text-align: left;">1.1 &nbsp;Thỏa thuận: là &ldquo;Thỏa thuận Cung ứng dịch vụ sàn thươ** mại điện tử&rdquo; được ký điện tử giữa hai bên, bao g&ocirc;̀m tài liệu thỏa thuận này và các Phụ lục (n&ecirc;́u có) đính kèm. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p>
            <p style="text-align: left;">1.2 &nbsp;Dịch vụ Ví điện tử: là dịch vụ do Myspa **** c&acirc;́p, cho phép người dùng sử dụ** Kênh thanh toán online đ&ecirc;̉ thanh toán sản ph&acirc;̉m/dị** vụ của ***** thô** qua các hình thức dùng ti&ecirc;̀n mặt hoặc không dùng ti&ecirc;̀n mặt.</p>
            <p style="text-align: left;">1.3 &nbsp;Kênh ***** toán online: là hệ th&ocirc;́** các Kênh thanh toán của MYSPA **** c&acirc;́p, đ&ecirc;̉ thực hiện Dịch vụ Ví điện tử *** g&ocirc;̀m và khô** giới hạn bởi các phương tiện và hình thức thanh toán như: Điện thoại di động, website, hệ th&ocirc;́ng các đi&ecirc;̉m thanh toán của MYSPA. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p>
            <p style="text-align: left;">1.4 &nbsp;Sản ph&acirc;̉m/dịch vụ: là dịch vụ chăm sóc sức khỏe, sắc đẹp do Người bán cung c&acirc;́p cho Người tiêu dù** khi Người tiêu dùng thực hiện giao dịch mua gói sử dụng dịch vụ, đặt lịch, mua thẻ thành viên trên Ứ** dụng Myspa beauty và Website https://beautyx.vn của Người bán theo đúng quy định của luật pháp và có nhu c&acirc;̀u sử dụng Kênh thanh toán online của MYSPA. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p>
            <p style="text-align: left;">1.5 &nbsp;Website và Ứng dụng : là website và ứ** dụng của MYSPA, do MYSPA quản lý và vận hành, cài đặt trên các thi&ecirc;́t bị ** động giúp Người tiêu dùng thực hiện các giao dị** mua sản ph&acirc;̉m/dịch vụ của Người bán d&ecirc;̃ dàng, thuận tiện hơn. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>
            <p style="text-align: left;">1.6 &nbsp;Người bán: là các đơn vị, t&ocirc;̉ chức cung c&acirc;́p dị** vụ chăm sóc sức khỏe, sắc đẹp cho Người tiêu dùng trên Ứng dụ** Myspa beauty và Website https://beautyx.vn của MYSPA, Người bán ủy quy&ecirc;̀n cho MYSPA nhận ti&ecirc;̀n từ Người tiêu dù** khi Người tiêu dùng thực hiện thanh toán Sản ph&acirc;̉m/dịch vụ do Người bán cung c&acirc;́p, theo đó MYSPA sẽ trực ti&ecirc;́p thực hiện đ&ocirc;́i soát và thanh quy&ecirc;́t toán với Người bán theo quy định tại Thỏa thuận này. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p>
            <p style="text-align: left;">1.7 &nbsp;Người tiêu dùng: là các cá nhân, t&ocirc;̉ chức đang có *** c&acirc;̀u sử dụ** sản ph&acirc;̉m/dịch vụ của Người bán. Người tiêu dùng có th&ecirc;̉ thanh toán cho Người bán thông qua Dịch vụ Ví điện tử. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p>
            <p style="text-align: left;">1.8 &nbsp;Giao dịch: là các giao dị** Người tiêu dùng thực hiện thanh toán các sản ph&acirc;̉m/dịch vụ của Người bán thông qua Kênh thanh toán ví điện tử căn cứ theo đi&ecirc;̀u khoản và đi&ecirc;̀u kiện của Thỏa thuận này.</p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<p style="text-align: left;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<p style="text-align: left;">1.9 &nbsp;Ứng dụng đa n&ecirc;̀n tảng : là Ứng dụng ví điện tử do đ&ocirc;́i tác MYSPA **** c&acirc;́p, quản lý và được Ngân hàng Nhà nước Việt Nam c&acirc;́p phép tri&ecirc;̉n **** dưới các thương hiệu ** đ&ocirc;́i tác MYSPA đăng ký. Đây là tài khoản điện tử trên hệ th&ocirc;́ng MYSPA mà chủ tài khoản có th&ecirc;̉ sử dụng và quản lý thông qua</p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<p style="text-align: left;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
        </div>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
    </div>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
</div>&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
</div>
<p>&nbsp; &nbsp;&nbsp;</p>
`