export const PLAT_FORM = {
    MOMO: "MOMO",
    TIKI: "TIKI",
    BEAUTYX: "BEAUTYX",
    MBBANK: "MBBANK",
    BEAUTYX_MOBILE: "BEAUTYX MOBILE",
    SHOPEE:"SHOPEE",
    VINID:"VINID"
}
export const PLAT_FORM_ARR = [
    PLAT_FORM.BEAUTYX,PLAT_FORM.MOMO, PLAT_FORM.TIKI, PLAT_FORM.MBBANK, PLAT_FORM.BEAUTYX_MOBILE,
    PLAT_FORM.SHOPEE, PLAT_FORM.VINID
]