export const paramOrgs = {
  limit: 15,
  'filter[keyword]': '',
  'filter[is_momo_ecommerce_enable]': '',
  'filter[is_moba_register_requested]': '',
  'filter[tags]': '',
  'filter[min_price]': '',
  'filter[max_price]': '',
  sort: '',
  include: 'tags|province|district|ward|branches|favorites|favorites_count',
}
export const paramApproves = {
  limit: 15,
  'filter[status]': '',
  'filter[approvable_type]': '',
  'filter[approvable_id]': '',
  'filter[organization.subdomain]': '',
  include: 'logs|organization|logs.employee.user',
  sort: '-created_at',
}
export const paramContract = {
  limit: 15,
  include: 'approve|organization',
  'filter[organization.subdomain]': '',
  sort: '-created_at',
}
export const paramOrder = {
  page: 1,
  limit: 15,
  'filter[status]': '',
  'filter[platform]': '',
  'filter[withServicesSold]': true,
  'filter[productable]': true,
  include: 'items|organization|branch|user|paymentMethod|deliveryAddress|appointments',
  sort: '-created_at',
  user_id: '',
  append: 'qr_link|origin',
}
export const paramService = {
  page: 1,
  limit: '15',
  'filter[keyword]': '',
  'filter[is_momo_ecommerce_enable]': '',
  'filter[location]': '',
  'filter[is_featured]': '',
  'filter[special_price]': '',
  'filter[special_price_momo]': '',
  'filter[min_price]': '',
  'filter[max_price]': '',
  'filter[special_min_price]': '',
  'filter[special_max_price]': '',
  'filter[special_min_price_ecommerce]': '',
  'filter[special_max_price_ecommerce]': '',
  'filter[discount_percent]': '',
  'filter[discount_percent_ecommerce]': '',
  sort: '',
}
export const paramProduct = {
  pgae: 1,
  limit: '15',
  'filter[keyword]': '',
  'filter[is_momo_ecommerce_enable]': '',
  'filter[location]': '',
  'filter[is_featured]': '',
  'filter[special_price]': '',
  'filter[special_price_momo]': '',
  'filter[min_price]': '',
  'filter[max_price]': '',
  'filter[special_min_price]': '',
  'filter[special_max_price]': '',
  'filter[special_min_price_ecommerce]': '',
  'filter[special_max_price_ecommerce]': '',
  'filter[discount_percent]': '',
  'filter[discount_percent_ecommerce]': '',
  sort: '',
}
