export const QR_KEY = {
  DISCOUNT_PAGE: "DISCOUNT_PAGE",
  DISCOUNT: 'DISCOUNT',
  DISCOUNT_CODE: 'DISCOUNT_CODE',
  BANNER: 'BANNER',
  PROMOTION: 'PROMOTION',
  COMMUNITY:'COMMUNITY',
  CUSTOMER:'CUSTOMER'
}
export const QR_CACHE = 15 * (60 * 1000)